# Generated by Django 3.1.5 on 2021-10-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exp', models.CharField(max_length=100)),
                ('any', models.CharField(max_length=100)),
                ('rate', models.IntegerField(verbose_name='10')),
            ],
        ),
    ]
